### ISSUE TITLE
Code Review I

### ISSUE THREAD

**Issue by Amanda111** [KuTuGu/Vue#1]
1. reset css不建议写在根组件里，webpack配置里加个css文件的loader
2. 项目还是建议使用css预处理器，scss了解一下
3.  **重点:** 没有复用组件；都是重复代码，看一下[mixin](https://vuejs.org/v2/guide/mixins.html)

**Comment by KuTuGu** [comment]
已改正。第一个好像不用配置css-loader；前两个用的比较少，mixin 很👍        
[仓库](https://github.com/KuTuGu/H5)

**Comment by KuTuGu** [comment]
[commit](https://github.com/KuTuGu/Vue/commit/862313256861e5deea75d81e6b53b3348f01a6c2)

**Comment by KuTuGu** [comment]
重新改正mixin，复用template；利用Vue.extend创建组件
[commit](https://github.com/KuTuGu/muxi-h5-gallery/commits/master)
